services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./backend/src/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
  backend:
    build: backend
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
